// JsFromRoutes CacheKey c8497e33a325d0bb35e7013dc974852a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as inertiaExample } from './InertiaExampleApi'
export { default as usersSessions } from './Users/SessionsApi'
export { default as usersPasswords } from './Users/PasswordsApi'
export { default as usersRegistrations } from './Users/RegistrationsApi'
export { default as dashboard } from './DashboardApi'
export { default as chat } from './ChatApi'
export { default as enrollments } from './EnrollmentsApi'
export { default as resources } from './ResourcesApi'
export { default as apiCourse } from './Api/CourseApi'
