// JsFromRoutes CacheKey b518fa099f5fe8a78a81a55c36808211
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as inertiaExample } from './InertiaExampleApi'
export { default as usersSessions } from './Users/SessionsApi'
export { default as usersPasswords } from './Users/PasswordsApi'
export { default as usersRegistrations } from './Users/RegistrationsApi'
export { default as dashboard } from './DashboardApi'
export { default as chat } from './ChatApi'
export { default as enrollments } from './EnrollmentsApi'
export { default as apiCourse } from './Api/CourseApi'
