// JsFromRoutes CacheKey c3a1fc3c87ac1fdaa6763e4534ec7b67
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as inertiaExample } from './InertiaExampleApi'
export { default as usersSessions } from './Users/SessionsApi'
export { default as usersPasswords } from './Users/PasswordsApi'
export { default as usersRegistrations } from './Users/RegistrationsApi'
export { default as dashboard } from './DashboardApi'
export { default as chat } from './ChatApi'
export { default as users } from './UsersApi'
export { default as enrollments } from './EnrollmentsApi'
export { default as resources } from './ResourcesApi'
export { default as apiCourse } from './Api/CourseApi'
export { default as apiFriendships } from './Api/FriendshipsApi'
