// JsFromRoutes CacheKey 289740171644930f261445e78e4e8ced
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  room: /* #__PURE__ */ definePathHelper('get', '/dashboard/room/:id/chat'),
  topic: /* #__PURE__ */ definePathHelper('get', '/dashboard/room/:id/topic/:topic_id/chat'),
}
