// JsFromRoutes CacheKey 2f5447df63306f5745a52a0b0c58bc39
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  room: /* #__PURE__ */ definePathHelper('get', '/dashboard/room/:id/chat'),
}
