// JsFromRoutes CacheKey 9cb6c812ba2d5b8a214137b327e55237
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/dashboard'),
  newRoom: /* #__PURE__ */ definePathHelper('get', '/dashboard/new_room'),
  explore: /* #__PURE__ */ definePathHelper('get', '/dashboard/explore'),
  showRoom: /* #__PURE__ */ definePathHelper('get', '/dashboard/room/:id'),
  createRoom: /* #__PURE__ */ definePathHelper('post', '/dashboard/create_room'),
}
