// JsFromRoutes CacheKey b34dba8c9455f6a68d4ae546e3760e9f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/enrollments'),
}
