// JsFromRoutes CacheKey 99bb64ac3a8914def569f18eaaf8eac8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/dashboard/room/:room_id/topic/:topic_id/resources'),
  create: /* #__PURE__ */ definePathHelper('post', '/dashboard/room/:room_id/topic/:topic_id/resources'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/dashboard/room/:room_id/topic/:topic_id/resources/:id'),
}
