// JsFromRoutes CacheKey 8415f3050e254eaa88eab18033f2df16
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/dashboard/user/:id'),
  index: /* #__PURE__ */ definePathHelper('get', '/dashboard/users'),
}
