// JsFromRoutes CacheKey 41a278299203384483c5a89556f8a7be
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/dashboard/user/:id'),
}
