// JsFromRoutes CacheKey 673f857422bfb030f9fc5ed6831032a6
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  subtopics: /* #__PURE__ */ definePathHelper('get', '/api/subtopics'),
}
