// JsFromRoutes CacheKey 43ea1a69a4f53ad8e9962366d879bcd7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  subtopics: /* #__PURE__ */ definePathHelper('get', '/api/subtopics'),
  updateProgress: /* #__PURE__ */ definePathHelper('patch', '/api/update-progress'),
}
