// JsFromRoutes CacheKey 9d9c00bc25f955e2618b1a2f28f46d16
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/api/add-friend'),
  accept: /* #__PURE__ */ definePathHelper('patch', '/api/accept-friend'),
}
