// JsFromRoutes CacheKey 89ae8d11be144f9123a7c907451fa476
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/users/sign_in'),
  create: /* #__PURE__ */ definePathHelper('post', '/users/sign_in'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/sign_out'),
}
